// <auto-generated />
using System;
using Gerenciador_de_espaçonaves_do_star_wars.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Gerenciador_de_espaçonaves_do_star_wars.Migrations
{
    [DbContext(typeof(StarWarsContext))]
    [Migration("20211004203353_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Gerenciador_de_espaçonaves_do_star_wars.Models.Nave", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Naves");
                });

            modelBuilder.Entity("Gerenciador_de_espaçonaves_do_star_wars.Models.Piloto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlanetaID")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("PlanetaID");

                    b.ToTable("Pilotos");
                });

            modelBuilder.Entity("Gerenciador_de_espaçonaves_do_star_wars.Models.Planeta", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Planetas");
                });

            modelBuilder.Entity("Gerenciador_de_espaçonaves_do_star_wars.Models.Viagem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataChegada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataSaida")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Naveid")
                        .HasColumnType("int");

                    b.Property<int?>("Pilotoid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Naveid");

                    b.HasIndex("Pilotoid");

                    b.ToTable("HistoricoViagens");
                });

            modelBuilder.Entity("Gerenciador_de_espaçonaves_do_star_wars.Models.Piloto", b =>
                {
                    b.HasOne("Gerenciador_de_espaçonaves_do_star_wars.Models.Planeta", "Planeta")
                        .WithMany()
                        .HasForeignKey("PlanetaID");
                });

            modelBuilder.Entity("Gerenciador_de_espaçonaves_do_star_wars.Models.Viagem", b =>
                {
                    b.HasOne("Gerenciador_de_espaçonaves_do_star_wars.Models.Nave", "Nave")
                        .WithMany()
                        .HasForeignKey("Naveid");

                    b.HasOne("Gerenciador_de_espaçonaves_do_star_wars.Models.Piloto", "Piloto")
                        .WithMany()
                        .HasForeignKey("Pilotoid");
                });
#pragma warning restore 612, 618
        }
    }
}
